"""Phase 5: Streak badges (4 badges).

Runs today's streak actions and generates a reusable daily script:
  - 7-Day Login Streak
  - 30-Day Login Streak
  - Submission Streak (7 days)
  - Super Submission Streak (30 days)

The script is generated for the user to schedule themselves if desired.
No cron jobs or launchd plists are installed automatically.
"""

import platform
import shlex
import stat
from pathlib import Path

from badge_tracker import set_status, should_attempt
from utils import SKILL_ROOT, STATE_DIR, TEMPLATES_DIR, get_kaggle_cli, run_kaggle_cli

if STATE_DIR == SKILL_ROOT:
    DAILY_SCRIPT_PATH = SKILL_ROOT / "modules" / "badges" / "scripts" / "daily_streak.sh"
else:
    DAILY_SCRIPT_PATH = STATE_DIR / "daily_streak.sh"


def _create_daily_script() -> Path:
    """Create the daily streak script (no credentials embedded)."""
    kaggle_cli = shlex.quote(get_kaggle_cli())
    submission_file = shlex.quote(str(TEMPLATES_DIR / "submission_titanic.csv"))

    script = f"""#!/usr/bin/env bash
# Daily Kaggle streak script — auto-generated by kaggle-badges
# Makes an API call (counts as login) and submits to Titanic
# Credentials are read by the Kaggle CLI at runtime; none are stored here.

set -uo pipefail

KAGGLE={kaggle_cli}
SUBMISSION={submission_file}
# The CLI prints request headers when VERBOSE is set; keep them out of logs.
unset VERBOSE VERBOSE_OUTPUT KAGGLE_API_ENVIRONMENT

# 1. API activity = login
if ! "$KAGGLE" datasets list --page 1 > /dev/null 2>&1; then
    echo "[$(date)] API call failed" >&2
fi

# 2. Daily Titanic submission (if submission file exists)
if [ -f "$SUBMISSION" ]; then
    if ! "$KAGGLE" competitions submit titanic \\
        -f "$SUBMISSION" \\
        -m "Daily streak submission $(date +%Y-%m-%d)" \\
        > /dev/null 2>&1; then
        echo "[$(date)] Titanic submission failed" >&2
    fi
fi

echo "[$(date)] Streak script completed"
"""
    DAILY_SCRIPT_PATH.parent.mkdir(parents=True, exist_ok=True)
    DAILY_SCRIPT_PATH.write_text(script)
    # Owner-only read/write/execute (no group or world access)
    DAILY_SCRIPT_PATH.chmod(stat.S_IRWXU)
    return DAILY_SCRIPT_PATH


def _run_today() -> bool:
    """Run today's streak actions inline. True when both actions succeeded."""
    print("  Running today's streak actions...")
    ok = True

    # 1. API activity (counts as login)
    result = run_kaggle_cli(["datasets", "list", "--page", "1"], check=False)
    if result.returncode == 0:
        print("    API login activity: OK")
    else:
        ok = False
        print("    API login activity: FAILED")

    # 2. Titanic submission
    submission_file = TEMPLATES_DIR / "submission_titanic.csv"
    if submission_file.exists():
        result = run_kaggle_cli(
            [
                "competitions",
                "submit",
                "titanic",
                "-f",
                str(submission_file),
                "-m",
                "Daily streak submission",
            ],
            check=False,
        )
        if result.returncode == 0:
            print("    Titanic submission: OK")
        else:
            ok = False
            print("    Titanic submission: FAILED")
    else:
        ok = False
        print(f"    Titanic submission: SKIPPED (no {submission_file})")

    return ok


def _print_scheduling_instructions(script_path: Path) -> None:
    """Print instructions for the user to set up their own daily scheduling."""
    system = platform.system()

    print("\n  --- Manual scheduling instructions ---")
    print(f"  Daily script created at: {script_path}")
    print()

    if system == "Darwin":
        print("  To schedule on macOS (launchd):")
        print("    1. Create a plist at ~/Library/LaunchAgents/com.kaggle.streak.plist")
        print(f"       with ProgramArguments pointing to: /bin/bash {script_path}")
        print("    2. Load it: launchctl load ~/Library/LaunchAgents/com.kaggle.streak.plist")
        print()
        print("  Or use cron:")
        print("    crontab -e   # then add:")
        print(f"    0 10 * * * {script_path}")
    else:
        print("  To schedule on Linux (cron):")
        print("    crontab -e   # then add:")
        print(f"    0 10 * * * {script_path}")

    print()
    print("  Credentials are read by the Kaggle CLI at runtime (API token,")
    print("  kaggle.json or OAuth login); none are stored in the script.")
    print("  Badges will be earned after 7/30 days of daily execution.")


def run(username: str) -> tuple[int, int]:
    """Run today's streak actions and generate reusable script.

    Returns (attempted, succeeded).
    """
    badge_ids = [
        "seven_day_login_streak",
        "thirty_day_login_streak",
        "submission_streak",
        "super_submission_streak",
    ]

    actionable = [b for b in badge_ids if should_attempt(b)]
    if not actionable:
        print("  All streak badges already earned/skipped")
        return 0, 0

    print("\n  --- Phase 5: Streak badges ---")

    # Run today's actions immediately
    today_ok = _run_today()

    # Generate the reusable daily script
    script_path = _create_daily_script()

    # Print instructions for manual scheduling
    _print_scheduling_instructions(script_path)

    # A streak is earned over 7 or 30 days, so nothing is earned today. The
    # badges stay "attempting"; run again with --resume to do the next day.
    details = (
        "today's actions done; repeat daily for the full streak"
        if today_ok
        else "today's actions failed; fix the error and run again"
    )
    for bid in actionable:
        set_status(bid, "attempting", details)

    return len(actionable), 0
